### ISSUE TITLE
Finding random items on ground in random areas with no marker indicating it is there

### ISSUE THREAD

**Issue by jaaaxxxx** [echoroleplay/feedback#15] opened 2023-05-29 18:15 UTC
**Description:** Whenever you look in your inventory in random areas of the city and houses, you will at times find random items. 

**Reproduction Steps:** 
1. Go into a house or anywhere after further investigation
2. Look in your inventory in different areas
3. Find random items that you did not drop

**Expected Behavior:** Not find random items such as keys, chop lists, bore hide, etc. inside of your house.

**Actual Behavior:** Random items in random spots without there being a blue arrow indicating they are there. 

**Screenshot(s)/Video(s):** https://i.imgur.com/HMa6spU.jpeg
https://i.imgur.com/mqZDdVf.jpeg
https://i.imgur.com/9mvUXx9.jpeg
https://i.imgur.com/IDuFhiG.jpeg
https://i.imgur.com/wsLmOIc.jpeg

**Comment by FlawwsX** [comment] 2023-05-30 12:21
This is a duplicate of https://github.com/echoroleplay/feedback/issues/8, closing this one.

**Closed by FlawwsX** 2023-05-30 12:21 UTC
Labels: bug, duplicate
