### ISSUE TITLE
Reduce the amount of crime that is gatekept

### ISSUE THREAD

**Issue by j1afridi** [echoroleplay/feedback#136] opened 2023-06-07 19:37 UTC
**Suggestion Description**
Let items needed for boosting and vangelicos more accessible to criminals who are not in gangs or "well-known" in the city.

**Reason**
There are people in the city who's roleplay is based around not being in a gang or they like to have secrecy that would still like to do jobs, and the state of the server right now is only drawing people away from doing crime. Not everyone wants to rob houses and smash/grab stores everyday it gets boring and there is only so much roleplay involved with that. I'm not saying things should be easy to acquire/craft but it shouldn't be so gatekept by this one guy Dr.Lamb and his associate. It just feels like a slap in the face to people who truly love the city and their roleplay involves boosting, robbing jewellery stores and interacting with cops etc and now they can't really do that without being someone special or in a gang.
**Additional context**
Also from what I've seen/heard from a cops perspective, sure they love traffic stop roleplay but now with this update they mald that they can't respond to their boosts to chase criminals and interact with them as they don't even happen or the person is already gone by the time they get there. Same story with the vangelicos and everything else. I'm only saying this because I truly love this server and the people who have made it/in it and as of now it feels more people including myself feel there is nothing to do.

**Comment by Innovation-0** [comment] 2023-06-07 23:37
I agree. Some people just dont want to interact with gangs especially after some negative interactions with them. Leaving out the crims that do their own RP with other solo crims really takes the fun out of meeting other non-gang people.

**Comment by damightylamb** [comment] 2023-06-07 23:45
This suggestion doesn't really provide any suggestion besides "change this because...". Would be better if you can come up with a suggestion that would make it better without involving boring mechanics like "crafting" just for people to grind. Also some things were/are limited AT THIS POINT because we are just fine tuning things and it will be more readily available soon. 

Interacting with someone directly creates more RP than "go somewhere to get thing now I can do crime".

**Comment by j1afridi** [comment] 2023-06-07 23:54
People go to you to get thing to do now they can do crime, what's the difference between going to a crafting table and having Dr.Lamb hand it to me in my hands. At least with crafting table I'd have to source items myself and roleplay with other people whether it be civs or crims in order to gain these materials now it's just you just have to know a guy who is the only key to doing crime.

**Comment by j1afridi** [comment] 2023-06-08 00:00
Grinding for materials was good RP, Benny Harris is one of many great examples to that. He is one of the most well-known people in the city through his business with grinding materials and selling them off to people in the city. It just sucks that one person decides what good RP is involving crime, grinding etc. It just seems like Dr. Lamb has control over everything and from my experience with other servers that is not the way to go and only pushes people away. Finally, it's not fair.

**Comment by damightylamb** [comment] 2023-06-08 00:01
`Grinding for materials was good RP` you lost me here.

**Comment by j1afridi** [comment] 2023-06-08 00:03
I appreciate you for taking my suggestion seriously, I'll know not to suggest anything again. It's a waste of breath.

**Comment by SurgeGit** [comment] 2023-06-08 00:04
Personally I think it would be cool if, similar to hacking, crafting required some kind of skill or knowledge that was only obtainable through RP. You would have to **learn** how to make explosives before you can craft it or make it yourself. There is also lots of ways RP to happen through the acquisition of the ingredients them self. The problem is not everyone wants to join a gang or involve themselves with gangs and there should be ways for small groups or single criminals to be successful without getting involved with larger gangs.

**Comment by damightylamb** [comment] 2023-06-08 00:04
You didn't suggest anything but "do this because". There are no solutions provided. If you look at my initial reply, I asked if you could provide something to fix rather than "do this because" https://github.com/echoroleplay/feedback/issues/136#issuecomment-1581661091

**Comment by j1afridi** [comment] 2023-06-08 00:06
This is a suggestion, I am suggesting a way where things aren't so gatekept and accessible to people. Surge made a great point.

**Comment by damightylamb** [comment] 2023-06-08 00:11
> This is a suggestion, I am suggesting a way where things aren't so gatekept and accessible to people. Surge made a great point.

But you provide no solution to it. Just saying "make things happen". It has already been decided by staff that crafting is not coming back, so unless you have a better solution than basic crafting, there isn't much to this suggestion.

**Comment by madness281991** [comment] 2023-06-08 00:12
So i ahve spoke to a few gangs and every time i speak with them they tell me that Dr Lamb tells them it has to be keep in there gang. That is strict rules set by Dr Lamb so i have been out there RP with the gangs to get stuff but i cant get anything as that is what they say every time i speak with them. So i feel like it dead end me keep trying as i every get is the same answer. As i use to order alot from the black market but now this has all changed i cant get anything what so ever

**Comment by damightylamb** [comment] 2023-06-08 00:12
> Dr Lamb tells them it has to be keep in there gang

This isn't true lol.

**Comment by madness281991** [comment] 2023-06-08 00:18
well this is what i have been told by a few of them that they are not aloud to let them leave the gangs. So i can see why this has been put in.

**Comment by brownbag13** [comment] 2023-06-08 00:41
> well this is what i have been told by a few of them that they are not aloud to let them leave the gangs. So i can see why this has been put in.

I have been told this too. When one person is running the black market, you must have a connection to him or you are simply out of luck. Favoritism plays into this heavily whether it is admitted or not. I am even in a gang that has been around for almost a year and still no luck. 

It is simply unfair to offer select individuals/gangs access to the new content. The city has been very tough to wake up in since not being able to do crime besides the small tier jobs.

**Comment by matt41631317** [comment] 2023-06-08 00:44
Same has been said to me as well, and im sure Dr. Lamb isnt telling them not to sell the items but why would they... gangs have a cap of 30 people ... they need the supplies... gangs are used to doing jobs but now jobs are non existant so now when dr lamb decides to bless someone cuz they are "worthy" of course they going to keep it VERY TIGHT AND VERY CLOSE TO HOME... I dont get how such DRASTIC changes get made without notifying us before hand too that all our previous green laptops red laptops encrypted sticks extend mags silencers would all become obsolete and to use them before a certain date or i dont know dont put them on the ORDERS the week before you decide to wipe them from the data base. I know people who have lost hundreds of thousands just off that... and the way theyve been tryna recoup that money is to do house robberies all day long because you literally cannot do anything else in this server but chop and rob houses. Its just insane to me that you cannot get a CHASE in ECHO RP without knowing dr lamb. A lot of us are here for the thrill of crime and to 80 percent of the city its been at an absolute stand still but then we get to here our favorite streamers getting dropped double digit amounts of thermite , random gangs being told by DR lamb to use items in certain ways or there will be consequences ... as in , insinuating that if it wasnt done they wouldnt be getting anymore supplies from him. It just seems like Dr lambs RP is focused on gangs and well known streamers in the city and all this SUGGESTION seems be is simply saying , its not right .. its not fair .. and for crafting not to be coming back.... I don't see how going through hours of physical acts of " grinding " materials with your friends or going to several different people trying to get the last min right item needed for a job. " isn't RP "  There were MANY avenues of RP regarding " crafting ". It's jus wild that you stop caring about suggestion once you saw someone say the word " grind " ... some people like the simple things ... as mentioned Benny Harris, there was an ENTIRE gang based around sourcing items the hobo gang .. to say that theres no RP around grinding and sourcing materials is just ignorant.

**Comment by Juhux** [comment] 2023-06-08 00:57
There has been plenty of suggestions on how to make crafting involve more RP/more steps and have the best of both worlds. For example thermite can be craftable but materials are much harder to get and require RP to obtain rather than ordering everything from Mecca. The thermite table can be locked behind a door(s) that need keys you need to RP to find and they could be obtainable from locations that change regularly every 1 week for example. Lots of ways to encourage RP AND lessen grinding and not lock stuff behind gangs.

**Comment by Acheron420** [comment] 2023-06-08 01:55
Just a lil feedback on criminal activities, more specifically solo crim.

A lot of changes were made recently, which is understandable, and some are really nice, but those are just side effects that will straighten out with time, and the current issue has been here for a while, one way or another really.

My routine playing this game is as follows, do some houses (barely any don't like to risk it too much), chop cars(boring af), try and rp a lil bit, and repeat. 
This is currently the cap a solo crim can reach; I've met a ton of people that shared some info, showed locations, etc. But that was it really; there is nothing a solo crim can contribute to getting a foot in the door.

I have no access to anything. Thus I can offer nothing to other crims to earn their trust and start networking. None of the materials is helpful to them, and they just don't need them.

Go southside and try to RP there? Good luck, they'll either provoke you and expect no retaliation, and if there is, you get mag dumped, and all you have is a Beretta that can't do jack.

Wanna get into racing? need someone who can sponsor you. How to meet that person? need them to trust you. How can they trust you? Well, draw of luck if you were to run into someone who happens to know someone. Which that in itself makes zero sense, as the lvl of entry to this specific one is already high (a decent car = expensive).

Wanna get into boosting? lol

Wanna try the new ATM hacking? pay a hefty price for a device cuz its being sprinkled down for some reason (the pay ain't even it)

Wanna network? immediately gets shut down, see above. 

This might be my experience, and tbh most people I've interacted with were cool. But when the mechanics are that micro managed, it leaves little room to move.

**Comment by Acheron420** [comment] 2023-06-08 02:03
With that being said, open the black market that's accessible on the laptop to be used by criminals to buy and sell stuff. Call it the silk market, make it where you need a password to get in maybe. But give players the ability to view/post deals. You can go on an Onion browser right now, and buy as many drugs as you want, among other things. So why not add it to the server, see how it goes. worst case scenario, just disable it.

**Comment by SurgeGit** [comment] 2023-06-08 02:42
You could also consider making a job for getting weapons/explosives and other heist related equipment. Like robbing an armory of some kind

**Comment by damightylamb** [comment] 2023-06-08 02:43
> You could also consider making a job for getting weapons/explosives and other heist related equipment. Like robbing an armory of some kind

already exists

**Comment by SurgeGit** [comment] 2023-06-08 02:45
so what is everyone talking about only getting it through Dr. Lamb then if you can get thermites like that

**Comment by Ooodee** [comment] 2023-06-08 02:52
I think hes talking about weapons, there is no job to get heist equipment which is a good suggestion tbh.

**Comment by brownbag13** [comment] 2023-06-08 02:55
> > You could also consider making a job for getting weapons/explosives and other heist related equipment. Like robbing an armory of some kind
> 
> already exists

cant get to this without being able to do the smaller heists though. Kinda our main problem here.

**Comment by SurgeGit** [comment] 2023-06-08 02:59
Gotcha. Could be a smaller one just for explosives or heist equipment for other things and not rifles or any other weapons that is more accessible to everyone.

**Comment by Morphiushell** [comment] 2023-06-08 04:26
I think staff provding the required items for specific jobs etc works when you have a dedicated staff team like we do here. I think the only concern I have is its not very lowkey in that everyone tags Dr.Lamb on twitter the moment they see his name so it gives cops less detective stuff to do when it becomes very clear that this character is a big piece of the puzzle.

A question I have is with regards to established and well trusted gangs via their RP etc have they ever been in a position to craft said items? This could be a nice alternantive way to provide more RP and less requirement from staff to be the ones providing it out to those deserving. What if X crew can craft Y item but their bench only allows Z number to be crafter weekly etc. I think this promotes RP between gangs and even those not in a gang when reaching out looking for these items.

**Comment by Phyl-Steamed** [comment] 2023-06-08 09:55
I would also say, as a suggestion, to use some of the "guides" that can be found somewhat around. Example would be the "melee guide" to then have some form of "tip" when using it, like using a note, which would have an image come up with a picture of the exterior of a building.
Then you take that with you to the area and upon finding the specific workbench, it allows you to use it, removing it from your inventory, and granting you a temporary access to the crafting of said item, or even 1 item of that type, for like, an entire storm, or a day, or a week (just like motels) and it makes it so you now have that additional blip.
And if all of those get scattered throughout the map, it would make it so each type of guide serves a purpose. Maybe adding an "explosive guide" for thermite, potentially an "electronic guide" for hacking devices, etc...

That's just a possibility that could create a crafting mechanic that's kept behind an item and behind a progression/unlocking of specific items throughout RP. It would mean that someone with the "rifle guide" would be valuable to sell rifles, or he could sell the info, but that still requires a guide of that type to be found and used in said area with the possibility of unlocking the rifle you wish.
But indeed, for a solo criminal character, there used to be a lot more than just houses. Now it's, houses and houses. And even selling materials has become obsolete.
Although I do believe it's a good direction to prevent just any newbie from joining the server, immediately gets informed of "buy a VPN, buy a tablet, buy a hacking device, get a driver/hacker and do boost" that was a really easy criminal activity to start while not supposed to be the "entry level".

**Comment by Balla44** [comment] 2023-06-08 13:02
A few takes here:

1.  Tagging Dr. Lamb on Twitter and YP is not great RP IMO. It boggles my mind that a criminal mastermind would allow people to so publicly out his business. It takes no time at all to realize exactly how important Dr. Lamb is and that seems counterproductive. 
**Suggestion:** Have an NPC somewhere where someone can pay EVC to get on a list and Dr. Lamb choses when/ if to contact. Can even implement a cooldown on the amount of times to enter the list or types of requests/ quests.  Yes this makes another NPC but it makes the entire process much more realistic to a criminal enterprise.
2. I understand the general sentiment behind grinding/ crafting as low RP but that is a bit short-sighted. Benny Harris recycling has already been mentioned here but you have to think about all of the other things we used to see on YP of various people selling materials, batteries, etc. Each one of those ads was a potential RP interaction. Yes. I am sure there were plenty of people who interacted with no one and grinded their own materials, but there is an entire group of RP ignored by taking that away. For example, I used to dumpster dive a LOT. Was there RP while I was doing it? Not really. BUT, I was able to make connections with several people and had routine customers across various groups just by myself. Another example: Was the mine comically flooded with Ore from people grinding Iron Oxide? Yes. BUT there was so much there people could scoop up excess and do the mining job and there is now an entire business trying to start up for custom jewelry based on mining material.   
**Suggestion** Combine the two systems. Have Dr. Lamb buy materials from people to "make" the other items. Use this as a way for solo crims to build up reputation with Dr. Lamb and eventually become a buyer or for just regular civs to have another income source/ method of RP.

**Comment by Lane2G** [comment] 2023-06-08 13:35
As a criminal no longer in a gang, who knew how to do everything before I have had Zero opportunity to move up into any jobs unless joining a gang (which I don’t want to at this time)ATMS are fun the first few times. No one sells thermite or the USBs needed for jobs and I don’t blame them. I’m hoping in time this is fixed but for the last two weeks of No progress it’s really disheartening. My suggestion would be rather then have just Dr.Lamb gangs should be allowed to have benches to make basic job items. bring back some grinding the market will figure itself out on pricing ect. This new way is just not it

**Comment by FlawwsX** [comment] 2023-06-19 17:22
We appreciate the feedback here and hope to have this resolved in approximately 2 weeks.

**Closed by FlawwsX** 2023-06-19 17:22 UTC
Labels: enhancement
