### ISSUE TITLE
House alarms

### ISSUE THREAD

**Issue by davidbnp** [echoroleplay/feedback#204] opened 2023-06-17 00:56 UTC
**Description:** After doing the system hack i either walk down the stairs or go through a door and the alarm goes off
**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Step one
Hack system, crouch walk downstairs or a little too much, or go through a door

**Expected Behavior:** hacking the system and not triggering the alarm over the tiniest thing.

**Actual Behavior:** You walk a little to weird, you walk downstairs, you walk through some doors and alarm goes off after doing a hack system

**Screenshot(s)/Video(s):** If possible, add screenshots or videos to help explain your problem.

**Comment by Ponnkun** [comment] 2023-06-18 21:22
This is a duplicate of issue #100

**Closed by Ponnkun** 2023-06-18 21:22 UTC
Labels: bug, duplicate
