### ISSUE TITLE
House Alarm Goes Off after successful hack

### ISSUE THREAD

**Issue by MrsTORN** [echoroleplay/feedback#207] opened 2023-06-17 11:34 UTC
**Description:** When you enter a 'Mid' or 'High-End' house to rob and disable the alarm, you walk around crouching quietly but the alarm still gets set off.

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Get House Robbery Job 
2. Successfully Disable Alarm
3. Start robbing like usual
4. The alarm will set off when you're near the front door or randomly

**Expected Behavior:** I Expected to disable the alarm and be able to walk around the house normally.

**Actual Behavior:** What actually happens is the alarm is still 'active' even after disabling it. 

**Screenshot(s)/Video(s):** 
Clip 1: Disabling the alarm - https://medal.tv/games/gta-v/clips/1ev71lndGCLXt2/FMuTEHuTf22X?invite=cr-MSxQSkUsMTg0MTk4MzQ3LA

Clip 2: Alarms gets set off after robbing a little - https://medal.tv/games/gta-v/clips/1ev7YTbUNEEQPA/sxw4ZzxAT16w?invite=cr-MSxNVkssMTg0MTk4MzQ3LA

**Comment by matt41631317** [comment] 2023-06-17 13:03
i just stopped robbing houses for this very point ..get a couple batteries and a vic and the alarm goes off ..like 3mins after i disable the alarm and have to use like trucks or vans for the new items ... walk outside VSTR , a bike cop... risk and reward there is so balanced , this is probably the 20th thread about it too.

**Comment by MrsTORN** [comment] 2023-06-17 13:24
> i just stopped robbing houses for this very point ..get a couple batteries and a vic and the alarm goes off ..like 3mins after i disable the alarm and have to use like trucks or vans for the new items ... walk outside VSTR , a bike cop... risk and reward there is so balanced , this is probably the 20th thread about it too.

tbh I wasn't sure if it was a bug or it was supposed to happen, but i guess the more 'reports' the higher chance it'll get noticed.

**Comment by TroyTates** [comment] 2023-06-17 14:58
ive had it on all houses apart from the forum drive ones frustrating to do the alarm system for it to go straight off after sucessful hack

**Comment by kaaycraay** [comment] 2023-06-17 17:10
It’s a known issue by the devs but one dev says it supposed to be like that… In my opinion the alarm should be turned off upon completing the hack. The hacks are pretty difficult already for a small reward. Also, there is RP blocking and W mentality when it comes to house robberies. I mean look at the queue on house robberies ZERO.

**Comment by SurgeGit** [comment] 2023-06-17 20:56
Just be patient I'm sure they are looking at it. Lots of people including myself have posted about it and it will be sorted. The queue used to be far too long and it got reduced and then when people started doing them they realised it was not feasible due to the alarm. When it's fixed the queue will be balanced out and if not it can be addressed

**Comment by Ponnkun** [comment] 2023-06-18 21:24
This is a duplicate of #100

**Closed by Ponnkun** 2023-06-18 21:24 UTC
Labels: bug, duplicate
