### ISSUE TITLE
Other peoples car poofing after storing in a penthouse that isn't theirs.

### ISSUE THREAD

**Issue by retures** [echoroleplay/feedback#144] opened 2023-06-08 22:34 UTC
**Description:** Please **replace me** with a description of the bug in as much detail as possible.

Have keys to a penthouse, and enter the garage with your car and park it. It says save and once you exit the garage and come back in it poofs. It sticks for the owner cars though.

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Have keys to a penthouse.
2. Take your car into the garage
3.  Store it
4. Walk out and back in.
5. Car not there

**Expected Behavior:** Detail what you expected to happen when you followed the steps above.
The car should be there ready to have so you can leave. But no car is there.

**Actual Behavior:**
 Car Poofs

**Screenshot(s)/Video(s):**
 Nothing in f8.

**Comment by davidxd33** [comment] 2023-06-08 23:40
If you park it in somebody's apartment, are you making sure you enter that specific garage and not your own?

**Comment by retures** [comment] 2023-06-09 02:01
yea ill send the video later

**Comment by davidxd33** [comment] 2023-06-12 12:18
If you manage to reproduce with a video please reopen this issue. Closing for now since it's unreproducible.

**Comment by Vallenesca** [comment] 2023-06-12 17:56
This still happens. In the supplied Video, you can se me enter and park the bike, leave, re-enter the garage and the bike is missing. Vehicle app says its parked, but its not there. 

https://streamable.com/4m69br

**Closed** 2023-06-12 21:52 UTC
Labels: bug
